version: '3.8'

services:
  unity:
    build: .
    container_name: unity
    environment:
      - UNITY_USERNAME
      - UNITY_PASSWORD
      - UNITY_SERIAL
    volumes:
      - ./:/app
    tty: true
